// Optional verification/artifact tool: npm install --no-save --package-lock=false playwright@1.56.1
// Run with the seeded Flask server on port 5000: node tools/browser_demo.cjs
process.env.PLAYWRIGHT_BROWSERS_PATH = require('path').resolve('.browser-cache');
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert');

(async () => {
  fs.mkdirSync('docs/screenshots', { recursive: true });
  fs.mkdirSync('docs/recordings', { recursive: true });
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, recordVideo: { dir: 'docs/recordings', size: { width: 1440, height: 1000 } } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const pause = () => page.waitForTimeout(2200);
  await page.goto('http://127.0.0.1:5000');
  await page.screenshot({ path: 'docs/screenshots/login-desktop.png', fullPage: true });
  await pause();
  await page.getByLabel('Email address').fill('demo@jobtrack.example');
  await page.getByLabel('Password', { exact: true }).fill('DemoPass123!');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await page.getByRole('heading', { name: 'Opportunity overview' }).waitFor();
  await page.screenshot({ path: 'docs/screenshots/dashboard-desktop.png', fullPage: true });
  await pause();
  await page.getByLabel('Search company or job title').fill('Orbit');
  await page.getByLabel('Filter status').selectOption('Interviewing');
  await page.getByRole('button', { name: 'Filter', exact: true }).click();
  assert(await page.getByText('1 results', { exact: true }).isVisible());
  await pause();
  await page.getByRole('link', { name: 'Reset', exact: true }).click();
  await page.getByRole('link', { name: '+ Add application' }).click();
  await page.getByLabel('Company', { exact: true }).fill('Willow Demo Studio');
  await page.getByLabel('Job title', { exact: true }).fill('Junior Python Developer');
  await page.getByLabel('Posting URL (optional)').fill('https://example.com/jobs');
  await page.getByLabel('Notes (optional)').fill('Prepare Flask portfolio. Ask about mentorship and code reviews.');
  await page.screenshot({ path: 'docs/screenshots/application-form-desktop.png', fullPage: true });
  await pause();
  await page.getByRole('button', { name: 'Save application' }).click();
  await page.getByRole('heading', { name: 'Willow Demo Studio' }).waitFor();
  await pause();
  await page.getByRole('link', { name: 'Edit application', exact: true }).click();
  await page.getByLabel('Status', { exact: true }).selectOption('Interviewing');
  await page.getByLabel('Notes (optional)').fill('Interview scheduled. Review SQL joins and Flask blueprints.');
  await page.getByRole('button', { name: 'Save application' }).click();
  assert(await page.getByText('Interview scheduled. Review SQL joins and Flask blueprints.', { exact: true }).isVisible());
  await page.screenshot({ path: 'docs/screenshots/application-detail-desktop.png', fullPage: true });
  await pause();
  await page.getByRole('link', { name: 'Delete application', exact: true }).click();
  await page.screenshot({ path: 'docs/screenshots/delete-confirmation.png', fullPage: true });
  await pause();
  await page.getByRole('link', { name: 'Keep application', exact: true }).click();
  assert(await page.getByRole('heading', { name: 'Willow Demo Studio' }).isVisible());
  await page.getByRole('link', { name: 'Delete application', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, delete application' }).click();
  assert(await page.getByText('Application deleted.', { exact: true }).isVisible());
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'docs/screenshots/dashboard-mobile.png', fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.getByRole('link', { name: '+ Add application' }).click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: 'docs/screenshots/application-form-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await pause();
  await page.getByRole('link', { name: 'Create an account' }).click();
  const email = 'walkthrough-' + Date.now() + '@example.com';
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Walkthrough123!');
  await page.getByLabel('Confirm password', { exact: true }).fill('Walkthrough123!');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByRole('link', { name: 'Add your first application' }).waitFor();
  await page.screenshot({ path: 'docs/screenshots/empty-dashboard.png', fullPage: true });
  await pause();
  await page.goto('http://127.0.0.1:5000/applications/1');
  assert(await page.getByText('We could not find that page or application.', { exact: true }).isVisible());
  await pause();
  await page.getByRole('link', { name: 'Back to dashboard', exact: true }).click();
  await pause();
  assert.deepStrictEqual(errors, []);
  const videoPath = await page.video().path();
  await context.close();
  fs.renameSync(videoPath, path.join('docs/recordings', 'jobtrack-walkthrough.webm'));
  await browser.close();
  console.log('Browser checks passed: authentication, CRUD, search/filter, deletion cancel/confirm, mobile overflow, empty dashboard, cross-account access. Screenshots and silent walkthrough saved.');
})().catch(error => { console.error(error); process.exit(1); });
